#cloud-config
# cloud-init devel schema --config-file cloud-init.yml

packages:
- curl
- wget
- apt-transport-https
- git
- vim
- tmux
- python3-pip
- docker.io
# don't use snap install docker, snap does something with context for docker builds

runcmd:
- pip3 install docker-compose
- timedatectl set-timezone CET
# https://www.scaleway.com/en/docs/how-to-mount-and-format-a-block-volume/
- lsblk -f|grep sda|grep -q ext4 || mkfs.ext4 /dev/sda
- mkdir -p /mnt/stateful
- mount -o defaults /dev/sda /mnt/stateful
# launch web ide (scw-userdata: https://blog.scaleway.com/2018/introducing-scaleway-cloud-init-support/)
- mkdir -p /srv/git
- cd /srv/git; git clone https://github.com/svlentink/dockerfiles.git
- cd /srv/git/dockerfiles/docker-compose/code-server; scw-userdata passwd > passdir/.passwd; ./init.sh; docker-compose up -d

final_message: "System up after $UPTIME sec."

