---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-schedule
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: svlentink/terraform-calendar
            workingDir: /app
            envFrom:
            - secretRef:
                name: env
            volumeMounts:
            - name: tf-cm
              mountPath: /app/.passwd
              subPath: .passwd
              readOnly: true
            - name: tf-cm
              mountPath: /app/cloud-init.yml
              subPath: cloud-init.yml
              readOnly: true
            - name: tf-cm
              mountPath: /app/main.tf
              subPath: main.tf
              readOnly: true
            - name: tfstate-pv
              mountPath: /tfstate
          volumes:
          - name: tf-cm
            configMap:
              name: tf-cm
              defaultMode: 0554
          - name: tfstate-pv
            hostPath:
              path: /tmp/tfstate
#            persistentVolumeClaim:
#              claimName: tfstate-pvc

