
# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: start-dev-env
spec:
  schedule: "2 12 * * 0-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: hashicorp/terraform:light
            workingDir: /app
            command: ["/docker-entrypoint.sh"]
            args:
            - apply
            envFrom:
            - secretRef:
                name: env
            volumeMounts:
            - name: tf-cm
              mountPath: /app/.passwd
              subPath: .passwd
              readOnly: true
            - name: tf-cm
              mountPath: /app/cloud-init.yml
              subPath: cloud-init.yml
              readOnly: true
            - name: tf-cm
              mountPath: /app/main.tf
              subPath: main.tf
              readOnly: true
            - name: tfstate-pv
              mountPath: /tfstate
            - name: tf-cm
              mountPath: /docker-entrypoint.sh
              subPath: docker-entrypoint.sh
          volumes:
          - name: tf-cm
            configMap:
              name: tf-cm
              defaultMode: 0554
          - name: tfstate-pv
            persistentVolumeClaim:
              claimName: tfstate-pvc

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stop-dev-env
spec:
  schedule: "55 18 * * 0-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: hashicorp/terraform:light
            workingDir: /app
            command: ["/docker-entrypoint.sh"]
            args:
            - destroy
            envFrom:
            - secretRef:
                name: env
            volumeMounts:
            - name: tf-cm
              mountPath: /app/.passwd
              subPath: .passwd
              readOnly: true
            - name: tf-cm
              mountPath: /app/cloud-init.yml
              subPath: cloud-init.yml
              readOnly: true
            - name: tf-cm
              mountPath: /app/main.tf
              subPath: main.tf
              readOnly: true
            - name: tfstate-pv
              mountPath: /tfstate
            - name: tf-cm
              mountPath: /docker-entrypoint.sh
              subPath: docker-entrypoint.sh
          volumes:
          - name: tf-cm
            configMap:
              name: tf-cm
              defaultMode: 0554
          - name: tfstate-pv
            persistentVolumeClaim:
              claimName: tfstate-pvc

