---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-machine-job
generatorOptions:
  disableNameSuffixHash: true

resources:
- cron.yml

configMapGenerator:
- name: tf-cm
  files:
  - main.tf
  - cloud-init.yml
  - .passwd

secretGenerator:
- name: env
  env: .env
  type: Opaque
