---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-machine-job
generatorOptions:
  disableNameSuffixHash: true

resources:
- pv.yml
- cron.yml
  pvc.yml

configMapGenerator:
- name: tf-cm
  files:
    - docker-entrypoint.sh
    - main.tf

secretGenerator:
- name: env
  files: .env
  type: Opaque
