---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfstate
  labels:
    type: local
    name: tfstate
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  # kubectl get sc
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/tfstate

