# https://microk8s.io/docs/addon-ingress
# https://github.com/ubuntu/microk8s/pull/1155
# https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-udp-microk8s-conf #udp-services
  namespace: ingress
data:
  53: "default/dns:53"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  53: "default/dns:53"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
#  selector:
#    matchLabels:
#      name: nginx-ingress-microk8s
  template:
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
        - containerPort: 80
        - containerPort: 443
        - name: proxied-udp-53
          containerPort: 53
          hostPort: 53
          protocol: UDP
