# https://kubectl.docs.kubernetes.io/pages/app_management/secrets_and_configmaps.html
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
generatorOptions:
  disableNameSuffixHash: true

resources:
#- pv.yml
- svc.yml
#- pvc.yml
- pod.yml

configMapGenerator:
- name: cm
  files:
  - docker-entrypoint.sh

