# https://kubectl.docs.kubernetes.io/pages/app_management/secrets_and_configmaps.html
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
generatorOptions:
  disableNameSuffixHash: true

resources:
- svc.yml
- pod.yml

configMapGenerator:
- name: cm
  namespace: dns
  files:
  - named.conf
  - zone.conf

