# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns
spec:
  selector:
    matchLabels:
      app: dns
  replicas: 1
  template: # create pods; pod template
    metadata:
      labels:
        app: dns
    spec:
      containers:
      - name: dns
        image: alpine
        env:
        - name: IPV4
          value: 212.47.228.126
        ports:
        - containerPort: 53
          protocol: UDP
        command:
        - /docker-entrypoint.sh
        volumeMounts:
        - name: cm
          mountPath: /docker-entrypoint.sh
          subPath: docker-entrypoint.sh
        - name: pv
          mountPath: /zones
      volumes:
      - name: cm
        configMap:
          name: cm
          defaultMode: 0554
      - name: pv
#        persistentVolumeClaim:
#          claimName: zones
#          readOnly: true
        hostPath:
          path: /mnt/k8s/ide/gits/myinfra/namespaces/dns/zones

