---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zones
  labels:
    name: zones
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  # kubectl get sc
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/k8s/ide/gits/myinfra/namespaces/dns/zones


