---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zones
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: microk8s-hostpath
  selector:
    matchLabels:
      name: zones

