# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#secretgenerator
# https://stackoverflow.com/questions/49614439/kubernetes-secret-types
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: main-tls
  files:
    - ~/.sekretoj/sslcerts/tls.cert # fullchain
    - ~/.sekretoj/sslcerts/tls.key  # privkey
  type: "kubernetes.io/tls"
- name: env_file_secret
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.
  env: env.txt
  type: Opaque

- name: basicauth-webide
  env: ~/.sekretoj/webIDE/.webIDE.env
  type: Opaque
