
runcmd:
  - apt install -y apt-transport-https curl
  - curl --silent -o /installall.sh https://raw.githubusercontent.com/svlentink/myinfra/master/main.sh
  - bash /installall.sh > /var/log/installall.log
