# https://kubectl.docs.kubernetes.io/pages/app_management/secrets_and_configmaps.html
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: dns-cm
  files:
  - named.conf
  - zone.conf
  - docker-entrypoint.sh

