# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#secretgenerator
# https://stackoverflow.com/questions/49614439/kubernetes-secret-types
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: main-tls
  files:
    - sslcerts/tls.crt # fullchain
    - sslcerts/tls.key  # privkey
  type: "kubernetes.io/tls"

