---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airport
generatorOptions:
  disableNameSuffixHash: true

resources:
- ing.yml
- svc.yml
- pod.yml

configMapGenerator:
- name: cm
  files:
  - scraper.py
  - listener.py
  - core.py

