---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: main
spec:
  schedule: "* * * * *"
  #schedule: "CRON_TZ=CET 11 1,2,3,4,5,6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never #OnFailure
          initContainers:
          - name: init
            image: debian:bullseye-slim
            command:
            - /entrypoint.sh
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: docker
            volumeMounts:
            - name: main-cm
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: main-cm
              mountPath: /tmp/list
              subPath: list.txt
              readOnly: true
            - name: cross-container
              mountPath: /kaniko/.docker
              readOnly: false
            - name: pv
              mountPath: /tmp/kaniko
          containers:
          - name: main
            image: gcr.io/kaniko-project/executor:debug
            command:
            - /kaniko/.docker/entrypoint
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: cross-container
              mountPath: /kaniko/.docker
            - name: pv
              mountPath: /tmp/kaniko
          volumes:
          - name: main-cm
            configMap:
              name: main-cm
              defaultMode: 0554
          - name: cross-container
            emptyDir:
              medium: Memory
          - name: pv
            hostPath:
              path: /tmp/kaniko

