---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: main
spec:
  #schedule: "*/5 * * * *"
  schedule: "11 1,2,3,4,5,6,7 * * *"
  #schedule: "CRON_TZ=CET 11 1,2,3,4,5,6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: init
            image: debian:bullseye-slim
            command:
            - sh
            - /entrypoint.sh
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: docker
            env:
            - name: TZ
              value: CET
            #- name: BUILD_ALL
            #  value: go-for-it
            volumeMounts:
            - name: main-cm
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: main-cm
              mountPath: /input-list
              subPath: list.txt
              readOnly: true
            - name: cross-container
              mountPath: /kaniko/.docker
              readOnly: false
            - name: stateful-list
              mountPath: /stateful-list-on-host
          containers:
          # The keep alive container is just there to make sure the main
          # container is restarted if there are multiple jobs to do
          # and the pod is set to BUILD_ALL
          #- name: keepalive
          #  image: alpine
          #  command:
          #  - sh
          #  - "-c"
          #  - 'while [ -n "`ls /kaniko/.docker/buildjobs`" ];do sleep 1; done' 
          - name: main
# https://github.com/GoogleContainerTools/kaniko/issues/1209#issuecomment-672184831
            image: gcr.io/kaniko-project/executor:debug #-v0.22.0
#            env:
#            - name: DOCKER_CONFIG
#              value: /kaniko/.docker/
            command:
            - /busybox/sh
            - /kaniko/.docker/entrypoint
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: cross-container
              mountPath: /kaniko/.docker
#            - name: kaniko-secret
#              mountPath: /kaniko/.docker
          volumes:
          - name: main-cm
            configMap:
              name: main-cm
              defaultMode: 0554
          - name: cross-container
            emptyDir:
              medium: Memory
# https://github.com/GoogleContainerTools/kaniko/blob/0477900febfacb98b88abdbfaf8bbaeb05f51060/examples/pod.yaml
#          - name: kaniko-secret
#            secret:
#             secretName: regcred
#             items:
#             - key: .dockerconfigjson
#               path: config.json
          - name: stateful-list
            hostPath:
              path: /var/kaniko-job
