---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: main
spec:
  schedule: "25 1,2,3,4,5,6,14 * * *"
  #schedule: "CRON_TZ=CET 11 1,2,3,4,5,6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never #OnFailure
          initContainers:
          - name: init
            image: debian:bullseye-slim
            command:
            - sh
            - /entrypoint.sh
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: docker
            volumeMounts:
            - name: main-cm
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: main-cm
              mountPath: /tmp/list
              subPath: list.txt
              readOnly: true
            - name: cross-container
              mountPath: /kaniko/.docker
              readOnly: false
          containers:
          - name: main
# https://github.com/GoogleContainerTools/kaniko/issues/1209#issuecomment-672184831
            image: gcr.io/kaniko-project/executor:debug #-v0.22.0
#            env:
#            - name: DOCKER_CONFIG
#              value: /kaniko/.docker/
            command:
            - /busybox/sh
            - /kaniko/.docker/entrypoint
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: cross-container
              mountPath: /kaniko/.docker
#            - name: kaniko-secret
#              mountPath: /kaniko/.docker
          volumes:
          - name: main-cm
            configMap:
              name: main-cm
              defaultMode: 0554
          - name: cross-container
            emptyDir:
              medium: Memory
# https://github.com/GoogleContainerTools/kaniko/blob/0477900febfacb98b88abdbfaf8bbaeb05f51060/examples/pod.yaml
#          - name: kaniko-secret
#            secret:
#             secretName: regcred
#             items:
#             - key: .dockerconfigjson
#               path: config.json

