---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: build-containers
spec:
  schedule: "11 1,2,3,4,5,6 * * *"
  #schedule: "CRON_TZ=CET 11 1,2,3,4,5,6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never #OnFailure
          containers:
          - name: main
            image: gcr.io/kaniko-project/executor:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: docker
            volumeMounts:
            - name: main-cm
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
            - name: main-cm
              mountPath: /tmp/list.txt
              subPath: list.txt
              readOnly: true
          volumes:
          - name: main-cm
            configMap:
              name: main-cm
              defaultMode: 0554

