---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaniko-job
generatorOptions:
  disableNameSuffixHash: true

resources:
- cron.yml

configMapGenerator:
- name: main-cm
  files:
  - entrypoint.sh
  - list.txt

secretGenerator:
- name: docker
  env: .env
  type: Opaque

