---
# https://github.com/kubernetes/ingress-nginx/issues/549
apiVersion: v1
data:
  hsts: "true"
  hsts-include-subdomains: "true"
  hsts-max-age: "0"
  hsts-preload: "false"
  ssl-protocols: "TLSv1.2 TLSv1.3"
kind: ConfigMap
metadata:
  namespace: ingress
# https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml
#  name: nginx-load-balancer-conf
  name: nginx-load-balancer-microk8s-conf

