
# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: main
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: python:alpine
            imagePullPolicy: IfNotPresent
            workingDir: /workdir
            command: ["/docker-entrypoint.sh"]
            volumeMounts:
            - name: output
              mountPath: /output
            - name: input
              mountPath: /input
              readOnly: true
            - name: workdir
              mountPath: /workdir
            - name: cm
              mountPath: /docker-entrypoint.sh
              subPath: docker-entrypoint.sh
          volumes:
          - name: cm
            configMap:
              name: cm
              defaultMode: 0554
          - name: workdir
            hostPath:
              path: /tmp/bookmarks-job-workdir
#            persistentVolumeClaim:
#              claimName: workdir
          - name: input
            hostPath:
              path: /mnt/k8s/ide/gits/pls/links
#            persistentVolumeClaim:
#              claimName: input
          - name: output
            hostPath:
              path: /mnt/k8s/ide
#            persistentVolumeClaim:
#              claimName: output

