---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookmarks-job
generatorOptions:
  disableNameSuffixHash: true

resources:
#- pv.yml
- cron.yml
#- pvc.yml

configMapGenerator:
- name: cm
  files:
  - docker-entrypoint.sh

