---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir
  labels:
    type: local
    name: workdir
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  # kubectl get sc
  storageClassName: microk8s-hostpath
  hostPath:
    path: /tmp/bookmarks-job-workdir

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: input
  labels:
    type: local
    name: input
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  # kubectl get sc
  storageClassName: microk8s-hostpath
  hostPath:
    path: /root/Dropbox/webIDE/gits/pls/links

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: output
  labels:
    type: local
    name: output
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  # kubectl get sc
  storageClassName: microk8s-hostpath
  hostPath:
    path: /tmp/bookmarks-job-output


