# https://kubectl.docs.kubernetes.io/pages/app_management/secrets_and_configmaps.html
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
generatorOptions:
  disableNameSuffixHash: true

resources:
- svc.yml
- pvc.yml
- pv.yml
- pod.yml

secretGenerator:
- name: airflow-env
  env: main.env
  type: Opaque
