---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scrape-strooikaart-job
generatorOptions:
  disableNameSuffixHash: true

resources:
- cron.yml

configMapGenerator:
- name: cm
  files:
  - docker-entrypoint.sh

