---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdn
generatorOptions:
  disableNameSuffixHash: true

resources:
#- pv.yml
- ing-http.yml
- ing-https.yml
- svc.yml
#- pvc.yml
- pod.yml

