---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdn
generatorOptions:
  disableNameSuffixHash: true

resources:
- ing-http.yml # very dangerous, because if auth fails, this is the fallback and it will be open to the world
- ing-https.yml
- svc.yml
- pod.yml

