---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-admin
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basicauth-wp
    nginx.ingress.kubernetes.io/auth-realm: 'Wordpress admin area'
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: lisanne.lent.ink
    http: &httpa_rules
      paths:
      - path: /wp-admin/
        pathType: Prefix
        backend:
          service:
            name: wp-proxy
            port:
              number: 80
  - host: juflisanne.nl
    http: *httpa_rules
  tls:
  - hosts:
    - lisanne.lent.ink
    - juflisanne.nl
    secretName: wp-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method !~ ^(GET|HEAD|OPTIONS)$ ) {
        return 444;
      }
spec:
  rules:
  - host: lisanne.lent.ink
    http: &http_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wp-proxy
            port:
              number: 80
  - host: juflisanne.nl
    http: *http_rules
  tls:
  - hosts:
    - lisanne.lent.ink
    - juflisanne.nl
    secretName: wp-tls


