---
# https://github.com/kubernetes/ingress-nginx/issues/549
apiVersion: v1
data:
  hsts: "false"
  hsts-include-subdomains: "false"
  hsts-max-age: "0"
  hsts-preload: "false"
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf

