# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ide
spec:
  selector:
    matchLabels:
      app: ide
  replicas: 1
  template: # create pods; pod template
    metadata:
      labels:
        app: ide
    spec:
      containers:
      - name: ide
        image: sapk/cloud9
# We overwrite forever with node since we want it to fail
# we had this issue with unreliable storage
# https://github.com/sapk/dockerfiles/blob/master/cloud9/Dockerfile.alpine
#        command: ["node", "/root/.c9/server.js", "-w", "/workspace", "--listen", "0.0.0.0"]
        args: ["--auth", ":"]
        ports:
        - containerPort: 8181
        volumeMounts:
        - name: ide
          mountPath: /workspace
      volumes:
      - name: ide
        persistentVolumeClaim:
          claimName: ide-claim


