---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ide
  labels:
    type: local
    name: ide
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  # kubectl get sc
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/k8s/ide

