---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: main
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildah: unconfined
spec:
  #schedule: "CRON_TZ=CET 11 1,2,3,4,5,6 * * *"
  schedule: "*/20 * * * *"
  #schedule: "11 1,2,3,4,5,6,7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never #OnFailure
          initContainers:
          - name: init
            #image: docker.io/svlentink/git:latest
            image: debian:latest #bullseye-slim
            command:
            - sh
            - /entrypoint.sh
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: docker
            env:
            - name: TZ
              value: CET
            volumeMounts:
            - name: main-cm
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: main-cm
              mountPath: /input-list
              subPath: list.txt
              readOnly: true
            - name: cross-container
              mountPath: /cross-container
              readOnly: false
            - name: stateful-list
              mountPath: /stateful-list-on-host
          containers:
          - name: buildah
            image: registry.access.redhat.com/ubi8/buildah:latest #8.10-1787721974
            command:
            - /bin/sh
            - /cross-container/.docker/entrypoint
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: cross-container
              mountPath: /cross-container
            resources:
              requests:
                ephemeral-storage: &size-limit 10Gi
              limits:
                ephemeral-storage: 20Gi
            securityContext:
              privileged: true
              allowPrivilegeEscalation: true
              seccompProfile:
                type: Unconfined
              #runAsUser: 0
              capabilities:
                add:
                - CAP_SYS_ADMIN
                - SYS_ADMIN

                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
                - SETFCAP
                - SYS_CHROOT
          volumes:
          - name: main-cm
            configMap:
              name: main-cm
              defaultMode: 0554
          - name: cross-container
            emptyDir:
              #medium: Memory
              sizeLimit: *size-limit
          - name: stateful-list
            hostPath:
              path: /var/container-builder-job
